### ISSUE TITLE
html2zim error

### ISSUE THREAD

**Issue by CharlesNepote** [MacroBull/html2zim#3]
clipcli is working fine. When I do the following command (under Ubuntu Linux), I have a good result:

```
$ ./clipcli.py text/html
��<pre><code>clipcli text/html</code></pre>
```

But html2zim doesn't work.

```
$ ./clipcli.py text/html -f ./index.html | ./html2zim.py -w /home/charles ./index.html
Traceback (most recent call last):
  File "./html2zim.py", line 432, in <module>
    sys.exit(main())
  File "./html2zim.py", line 424, in main
    buf = open(sys.argv[1]).read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

Any idea?

**Comment by MacroBull** [comment]
That's one of Python2 headaches, try to port the code into Python3 and have a try?
Long time since my last time using Zim, this project is paused in development.

**Comment by CharlesNepote** [comment]
Hi MacroBull,

In fact the problem comes from Firefox which provide UTF-16LE data while Chrome provide UTF-8 or ASCII data. I found two solutions.

**The first one** is to use iconv in the pipe, for example:

```
./clipcli.py -f ~/clip.html text/html ; iconv -f UTF-16LE -t UTF-8 -o ~/clip.html ~/clip.html ; ./html2zim.py -w ./ ~/clip.html
```

iconv is only used when you copy/paste from Firefox. Don't use it with Chrome.

**The second one** is more powerfull, using the chardet python library in the clipcli.py script.

``` python
''' import chardet at the beginning of the script and then modify the following function'''
def format_contents(contents):
    encoding = chardet.detect(contents.data)['encoding']
    if contents.type == 'INTEGER':
        from struct import unpack
        # This would be useful for the 'TIMESTAMP' target
        #   if the integers returned were UNIX timestamps.
        # However they seem to be negative numbers.
        # As it is,
        #   I have no idea what the byte order and size can be expected to be,
        #   and haven't found documentation about how to interpret the value.
        # This mostly just prevents unprintables from being output.
        return str(unpack('i', contents.data[:4])[0])
    elif re.match('text/.*ml', namespace.target):
#       return xml.dom.minidom.parseString(contents.data.rstrip('\0')).toprettyxml(indent="\t")
#       return contents.data.replace('>', '>\n')
        return contents.data.decode(encoding)
    else:
        return contents.data.decode(encoding)
```

Now the script works both with Firefox and Chrome.

Do you want me to create a Pull request? If you don't want to continue this project anymore, do you allow me to fork it and create a new official repo (of course I will mention your the original author of the script)?

**Comment by MacroBull** [comment]
You can fork it if you like to
